version: '3'
services:  
  cram:
    image: "arthurniedz/cram:latest"
    container_name: cram_container
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - ./lectures:/home/cram_lectures
    network_mode: host
